### ISSUE TITLE
关于 topos 的中文译名

### ISSUE THREAD

**Issue by YiqiXu** [Trebor-Huang/history#1]
请问“意象”作为 topos 的中文译名有共识吗？你知道最初是谁给出了这个译名吗？它和文学领域的意象（英译 topos）有任何联系吗？

**Comment by kokic** [comment]
关于前两个问题: 目前似乎存在一些共识,  可能的来源是  [1. 凝聚态集 - 香蕉空间](https://www.bananaspace.org/wiki/讲义:凝聚态数学/凝聚态集) 及 [意象 - 香蕉空间](https://www.bananaspace.org/wiki/意象) (虽然是一个人). 

在此讲义的第5章 ([5. 凝聚态生象 - 香蕉空间](https://www.bananaspace.org/wiki/讲义:凝聚态数学/凝聚态生象)) 还将 “anima” 翻译为生象. 这些翻译最初可能只是为了方便讨论班内部使用而拟定的, 在凝聚态数学讲义编写早期我并未在其他地方见过此种翻译, 往往是直接使用 “topos” 一词或音译为 “拓扑斯”.

**Comment by YiqiXu** [comment]
感谢你的参考链接。你知道给出这个译名的理由吗？

**Comment by Trebor-Huang** [comment]
> 请问“意象”作为 topos 的中文译名有共识吗？你知道最初是谁给出了这个译名吗？它和文学领域的意象（英译 topos）有任何联系吗？

我认识另一个自称是他首先提出的。但是很有可能还有一些人提出了这个，就看是谁影响力大了

**Comment by Trebor-Huang** [comment]
词源上看Grothendieck是直接将拓扑这个词缩短变成了topos，但是它长得非常像希腊词。后面有一两个有名的数学家非常喜欢希腊词，所以开始使用topoi作为复数，以及发明了logos之类的对应词。topos和logos在文学中都有

**Comment by YiqiXu** [comment]
我很想知道他们如此翻译的原因，因为我其实无法赞同这个翻译。

**Comment by kokic** [comment]
> 我很想知道他们如此翻译的原因，因为我其实无法赞同这个翻译。

“无法赞同” 这是正常的, 有相当一部分人都持有这样的观点. 而如此翻译的原因也许只有直接询问首倡者才能得知. 特别是取 “文学领域的意象” 一译, 这种原因颇有可能, 在历史上也不乏此类例子.

**Comment by Trebor-Huang** [comment]
拓扑这个词音意兼具，拓扑斯就只有音没有意。
topos一词单说一般指初等topos，来源与几何没有关系，所以这导致拓扑斯这个词里面携带的拓扑成了累赘。因此意象这个翻译是好于拓扑斯。不排除有更好的翻译

**Comment by YiqiXu** [comment]
> topos一词单说一般指初等topos，来源与几何没有关系

1. Topos 由 Grothendieck 首先定义，作为拓扑空间的极广泛的推广，诞生之初格老就将它视为一种广义空间，其几何的本质毋庸置疑。而 elementray topos 只是 Lawvere 和 Tierney 在此基础上从 ETCS 提炼出来的结构，仅仅是一个次生概念。我无法赞同“与几何没有关系”的断言。
2. Elementray topos 这个概念隐匿了 site 这个格老多次强调的重要概念，不仅弱化了其几何特性，还丧失了链接不同领域（特别是几何领域）的桥梁功能，导致 topos theory 专家与几何专家分道扬镳近半个世纪。我觉得在中文译名里再次忽略 topos 的几何特性只会加深这种隔阂，导致更多误解。
3. 名字里虽有 elementary，但并不代表 elementray topos 这个概念更基本，不少专家抱怨过这个问题。
4. 我认为不存在“topos一词单说一般指初等topos”这种共识。随着 Caramello 把 topos theory 带回数学家的视野，许多专家都同意，相比 elementray topos， Grothendieck topos 更具有中心地位，这是格老原始的想法。
5. 如果你基于 _Elephant_ 认为“topos一词单说一般指初等topos”，必须指出这是 Johnstone 的个人观念。他在 Topos Theory 书中甚至认为 classifying toposes of geometric theories 是无用的概念，也说明了他一直忽视 syntactic site 的概念。作为顶级专家，这种意义上，他促进了第二点里的状况。
6. 这和 ∞-category theory 里的术语不一致，∞-topos 通常指 Grothendieck ∞-topos.

> 拓扑斯就只有音没有意。

根据之前的说明，我认为“拓扑斯”里的“拓扑”拥有明确的含义，强调了 topos 作为广义空间的一方面。

最后，我不同意借用或挪用别的领域的术语，此外“意象”还是日常用语，恐造成意想不到的各种误解，TeXmacs 就是极糟的例子。Topos 作为格老认为的核心概念，值得拥有一个独一无二的译名。

综上，我认为“拓扑斯”是比“意象”更好的译名，当然也不是最理想的。

PS. 基于同样的原因，将 site 译为“景”也不合适。

**Comment by LongkeTang** [comment]
> 

我不是提出意象的人，不过目前是主要使用者。我认为你说的不是什么问题，因为意象足够独一无二，作为核心概念的译名完全够格，且虽是自然语言词汇但在数学中使用并不会混淆。如因为是自然语言而拒绝意象，那么群环域模就都死了。当然我同意Grothendieck意象比初等意象更具中心地位。

**Comment by LongkeTang** [comment]
另外并不是说作为字符串包含“拓扑”就更能表达广义空间的含义。景自然也有空间含义，而数学上意象是景的抽象，是景的本质信息，不同的景可以给出同样的意象，好比图册和流形，这也符合这两个词在自然语言中的含义。相比之下它和拓扑空间在数学上倒没离得那么近，只是一部分拓扑空间对应于一部分0-意象。

**Comment by YiqiXu** [comment]
@LongkeTang 很遗憾，我无法认同你的解释，可惜最近有点忙，过段时间我再详细解释。

**Comment by Trebor-Huang** [comment]
如果要改那需要先把位象和生象的翻译全部配套敲定，翻译成“洛开”，“阿尼玛”就太搞笑了
