### ISSUE TITLE
关于“连续域”

### ISSUE THREAD

**Issue by YiqiXu** [Trebor-Huang/history#2]
第33页中，

> 譬如域在没有排中律的时候会出现离散域与**连续域**的变体, 有理数 ℚ 是离散域, 而实数 ℝ 则是**连续域**.

就我所知，“连续域”并不是标准术语（如果我遗漏了，欢迎分享文献，谢谢）；而且根据实数不同的定义，实数可以拥有（在构造主义下）不等价的结构，似乎没有一个统一概念可以统揽。此处似乎加一个更细致的脚注为妙。

**Comment by Trebor-Huang** [comment]
连续域就是Heyting field的翻译。我没有找到任何已有的翻译，连“Heyting域”这个词都没找到。

这一段的目标读者是从没听过构造主义逻辑的人，不应该添加过多细节。

**Comment by YiqiXu** [comment]
> 实数 ℝ 则是连续域.

那么这句话就不严谨了，至少应该注明使用了哪种实数定义。

**Comment by Trebor-Huang** [comment]
> > 实数 ℝ 则是连续域.
> 
> 那么这句话就不严谨了，至少应该注明使用了哪种实数定义。

真的么？我印象中所有的实数版本都符合连续域的定义。

**Comment by YiqiXu** [comment]
MacNeille 实数只能构成 a residue field，而并非所有 residue fields 都是 Heyting fields.

**Comment by Trebor-Huang** [comment]
Ok, 我没考虑到这个
