### ISSUE TITLE
1.3 第五、六頁 缺少參照

### ISSUE THREAD

**Issue by dannypsnl** [Trebor-Huang/history#5]
第五頁的
 
> - 从 S 到集合范畴 Set 的保积函子与群一一对应.
> - ...

S 似乎沒有定義或是來源？前面提到的變數只有

> 我们考虑一列群 Fn(n ∈ N), 即有 n 个生成元的 自由群. 它们之间的群同态构成一个范畴. 我们取这个范畴的对偶 T

**Comment by Trebor-Huang** [comment]
笔误
