### ISSUE TITLE
用詞模糊之處

### ISSUE THREAD

**Issue by dannypsnl** [Trebor-Huang/history#9]
在

https://github.com/Trebor-Huang/history/blob/66eb23c67428701bcec79cf142c397b9c6cbafdc/chapters/martin-lof.tex#L406

這裡是說使用者安插說明幫助軟體判斷，是否是指幫助使用者在提示中選擇的用法？

**Comment by Trebor-Huang** [comment]
例如某处已经提前证明 $p : \zeta(2) = \pi^2/6$. 假设此时有 $P : \mathbb R \to \textsf{Type}$, 并且用户需要填入 $P(\zeta(2))$, 那么用户可以在此处插入提示 `consider p in (...)`, 那么软件会将 $p$ 纳入考量范围，此时省略号处只需填入 $P(\pi^2/6)$ 即可
